import { Router } from 'express';
import bcrypt from 'bcryptjs';
import { User } from '../models/index.js';
import { protect } from '../middleware/auth.js';
import { signToken, safeUser } from '../utils/token.js';
const router = Router();
router.post('/register', async (req, res) => { const { name, email, password, phone, address } = req.body; if (!name || !email || !password) return res.status(400).json({ success: false, message: 'Name, email and password are required' }); if (await User.findOne({ email })) return res.status(409).json({ success: false, message: 'Email is already registered' }); const user = await User.create({ name, email, password: await bcrypt.hash(password, 12), phone, address }); res.status(201).json({ success: true, data: { user: safeUser(user), token: signToken(user.id) } }); });
router.post('/login', async (req, res) => { const user = await User.findOne({ email: req.body.email }); if (!user || !(await bcrypt.compare(req.body.password || '', user.password))) return res.status(401).json({ success: false, message: 'Invalid email or password' }); res.json({ success: true, data: { user: safeUser(user), token: signToken(user.id) } }); });
router.post('/logout', (req, res) => res.json({ success: true, message: 'Logged out successfully' }));
router.get('/me', protect, (req, res) => res.json({ success: true, data: req.user }));
export default router;
