import { Router } from 'express';
import { Category } from '../models/index.js';
import { protect, adminOnly } from '../middleware/auth.js';
const router = Router();
router.get('/', async (req, res) => res.json({ success: true, data: await Category.find() }));
router.get('/:id', async (req, res) => { const category = await Category.findById(req.params.id); if (!category) return res.status(404).json({ success: false, message: 'Category not found' }); res.json({ success: true, data: category }); });
router.post('/', protect, adminOnly, async (req, res) => res.status(201).json({ success: true, data: await Category.create(req.body) }));
router.put('/:id', protect, adminOnly, async (req, res) => { const category = await Category.findByIdAndUpdate(req.params.id, req.body, { new: true, runValidators: true }); if (!category) return res.status(404).json({ success: false, message: 'Category not found' }); res.json({ success: true, data: category }); });
router.delete('/:id', protect, adminOnly, async (req, res) => { await Category.findByIdAndDelete(req.params.id); res.json({ success: true, message: 'Category deleted' }); });
export default router;
