import bcrypt from 'bcryptjs';
import connectDatabase from './config/db.js';
import { User, Category, Product } from './models/index.js';
const categories = [['Workspace', 'Tools for a sharper desk'], ['Audio', 'Immersive sound for every day'], ['Wearables', 'Thoughtful tech, worn well'], ['Home', 'Small upgrades, big comfort'], ['Mobile', 'Power that travels'], ['Gaming', 'Play without compromise']];
const products = [
	['Aero Mechanical Keyboard', 'Quiet tactile keys with a compact aluminum frame', 129, 15, 'Keyform', 'Workspace'],
	['Halo ANC Headphones', 'Adaptive noise cancelling with 40-hour battery', 249, 22, 'Sonic Labs', 'Audio'],
	['Orbit Smartwatch', 'Health insights and notifications in a slim case', 189, 18, 'Orbit', 'Wearables'],
	['Luma Desk Lamp', 'Warm, adjustable light with wireless charging', 89, 30, 'Luma', 'Home'],
	['Pulse USB-C Hub', 'Seven ports in a travel-ready body', 69, 40, 'Nova', 'Mobile'],
	['Vector Controller', 'Precise haptics and all-day comfort', 79, 24, 'Vector', 'Gaming'],
	['Atlas Standing Desk', 'Electric height control and a bamboo worktop', 599, 8, 'Formwork', 'Workspace'],
	['Slate Monitor Arm', 'Balanced gas-spring arm for a clean setup', 149, 20, 'Formwork', 'Workspace'],
	['Mica Desk Mat', 'Recycled felt surface with a stitched edge', 39, 45, 'Mica', 'Workspace'],
	['North Field Notebook', 'Lay-flat dot grid notebook for clear thinking', 18, 60, 'North Field', 'Workspace'],
	['Arc Webcam', 'Sharp video with a privacy shutter and mic array', 99, 19, 'Arc', 'Workspace'],
	['Cove Cable Tray', 'Under-desk cable storage in powder-coated steel', 44, 32, 'Cove', 'Workspace'],
	['Frame Task Chair', 'Supportive mesh chair with adjustable lumbar', 429, 11, 'Frame', 'Workspace'],
	['Nook Laptop Stand', 'Fold-flat aluminum stand for a better angle', 59, 38, 'Nook', 'Workspace'],
	['Grid Power Bar', 'Surge protection with USB-C fast charging', 64, 27, 'Grid', 'Workspace'],
	['Echo Bluetooth Speaker', 'Room-filling sound in a compact waterproof body', 119, 25, 'Sonic Labs', 'Audio'],
	['Drift Turntable', 'Wireless record player with a warm preamp', 279, 9, 'Drift', 'Audio'],
	['Sonar Desktop Speakers', 'Balanced stereo sound for focused listening', 199, 14, 'Sonar', 'Audio'],
	['Quiet Loop Earbuds', 'Small case, clear calls, and adaptive silence', 139, 35, 'Quiet Loop', 'Audio'],
	['Lowline Soundbar', 'Wide dialogue-forward sound for movie nights', 329, 12, 'Lowline', 'Audio'],
	['Tempo Studio Mic', 'USB condenser mic for calls and recording', 149, 18, 'Tempo', 'Audio'],
	['Morrow Sleep Buds', 'Comfort-first audio for a calmer night', 159, 16, 'Morrow', 'Audio'],
	['Ridge Portable DAC', 'Detailed wired listening from any phone', 109, 29, 'Ridge', 'Audio'],
	['Mono Radio', 'A tactile internet radio for slow mornings', 129, 21, 'Mono', 'Audio'],
	['Phase Audio Cable', 'Braided low-noise cable with metal connectors', 29, 70, 'Phase', 'Audio'],
	['Vale Fitness Band', 'Lightweight activity tracking with seven-day battery', 79, 31, 'Vale', 'Wearables'],
	['Arc Field Watch', 'Minimal analog watch with a durable steel case', 219, 13, 'Arc', 'Wearables'],
	['Pulse Ring', 'Subtle sleep and recovery insights', 299, 10, 'Pulse', 'Wearables'],
	['Lumen Clip Light', 'Rechargeable reading light with three temperatures', 35, 44, 'Lumen', 'Wearables'],
	['Trail GPS Watch', 'Reliable route tracking for weekend adventures', 329, 12, 'Trail', 'Wearables'],
	['Morrow Sleep Mask', 'Contoured blackout mask with a soft finish', 49, 36, 'Morrow', 'Wearables'],
	['Loop Smart Tag', 'Find keys, bags, and the things that wander', 25, 75, 'Loop', 'Wearables'],
	['Form Camera Strap', 'Comfortable woven strap with quick-release clips', 42, 27, 'Form', 'Wearables'],
	['Civic Bike Light', 'Bright USB-C light with automatic braking mode', 55, 33, 'Civic', 'Wearables'],
	['Aura Health Scale', 'A clear view of everyday body metrics', 89, 23, 'Aura', 'Wearables'],
	['Cloud Throw', 'Soft woven throw for a quiet corner', 74, 20, 'Cloud', 'Home'],
	['Solis Diffuser', 'Ultrasonic diffuser with a gentle ambient light', 59, 28, 'Solis', 'Home'],
	['Kite Air Purifier', 'Quiet filtration for bedrooms and studios', 229, 13, 'Kite', 'Home'],
	['Wren Electric Kettle', 'Fast boil with a precise pour spout', 109, 17, 'Wren', 'Home'],
	['Still Ceramic Set', 'Four handmade cups with a satin glaze', 64, 21, 'Still', 'Home'],
	['Onda Coffee Scale', 'Accurate timing and weight for better brews', 79, 26, 'Onda', 'Home'],
	['Hearth Candle Set', 'Three clean scents in reusable glass jars', 48, 34, 'Hearth', 'Home'],
	['Moss Plant Sensor', 'Simple moisture readings for happier plants', 32, 41, 'Moss', 'Home'],
	['Rove Travel Blanket', 'Packable warmth for flights and train rides', 89, 19, 'Rove', 'Home'],
	['Cedar Storage Tray', 'Solid wood catch-all for keys and small objects', 52, 24, 'Cedar', 'Home'],
	['Volt GaN Charger', 'Compact 100W charging for a full tech kit', 89, 42, 'Volt', 'Mobile'],
	['Roam Mag Battery', 'Magnetic wireless power for long days out', 69, 37, 'Roam', 'Mobile'],
	['Fold Travel Stand', 'Pocket-sized phone stand with a solid hinge', 24, 58, 'Fold', 'Mobile'],
	['Signal 5G Router', 'Fast, flexible internet for home or travel', 249, 16, 'Signal', 'Mobile'],
	['Port USB-C Cable', 'Durable braided cable with a two-year warranty', 22, 80, 'Port', 'Mobile'],
	['Cove Privacy Screen', 'Easy-fit screen for focused public work', 45, 31, 'Cove', 'Mobile'],
	['Atlas Tablet Sleeve', 'Padded recycled fabric sleeve with a slim profile', 49, 35, 'Atlas', 'Mobile'],
	['Nova Travel Adapter', 'Universal adapter with two fast USB-C ports', 59, 27, 'Nova', 'Mobile'],
	['Link Multi Charger', 'One tidy station for phone, watch, and earbuds', 119, 18, 'Link', 'Mobile'],
	['Wayfinder Tracker', 'Long-range location tag with replaceable battery', 39, 46, 'Wayfinder', 'Mobile'],
	['Apex Wireless Mouse', 'Precise silent clicks with an ergonomic shell', 69, 33, 'Apex', 'Gaming'],
	['Forge Gaming Keyboard', 'Low-latency switches and programmable controls', 159, 17, 'Forge', 'Gaming'],
	['Nova 27 Monitor', 'Fast IPS panel with rich color and clean lines', 349, 10, 'Nova', 'Gaming'],
	['Rift Racing Wheel', 'Force feedback wheel for immersive racing', 399, 7, 'Rift', 'Gaming'],
	['Beacon Desk Light', 'Screen-friendly light with reactive scenes', 99, 22, 'Beacon', 'Gaming'],
	['Core XL Mousepad', 'Smooth control surface with stitched edges', 39, 43, 'Core', 'Gaming'],
	['Switch Capture Card', 'Low-latency capture for streaming setups', 169, 14, 'Switch', 'Gaming'],
	['Haven Gaming Chair', 'Supportive recline with breathable upholstery', 299, 9, 'Haven', 'Gaming'],
	['Quest Handheld Case', 'Protective case with room for accessories', 45, 29, 'Quest', 'Gaming'],
	['Link Gamepad Dock', 'Weighted charging dock for two controllers', 59, 18, 'Link', 'Gaming']
];
await connectDatabase();
await User.findOneAndUpdate({ email: 'admin@novacart.local' }, { name: 'NovaCart Admin', email: 'admin@novacart.local', password: await bcrypt.hash('Admin123!', 12), role: 'admin' }, { upsert: true, new: true });
for (const [name, description] of categories) await Category.findOneAndUpdate({ name }, { name, description }, { upsert: true, new: true });
for (const [name, description, price, stock, brand, categoryName] of products) { const category = await Category.findOne({ name: categoryName }); await Product.findOneAndUpdate({ name }, { name, description, price, stock, brand, discount: price > 200 ? 10 : 0, image: `https://images.unsplash.com/photo-1498049794561-7780e7231661?w=900&q=80`, categoryId: category.id }, { upsert: true, new: true }); }
console.log(`Seed complete: ${products.length} products. admin@novacart.local / Admin123!`); process.exit(0);
