import 'express-async-errors';
import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import connectDatabase from './config/db.js';
import authRoutes from './routes/auth.js';
import productRoutes from './routes/products.js';
import categoryRoutes from './routes/categories.js';
import cartRoutes from './routes/cart.js';
import orderRoutes from './routes/orders.js';
import reviewRoutes from './routes/reviews.js';
import userRoutes from './routes/users.js';
import wishlistRoutes from './routes/wishlist.js';
import { notFound, errorHandler } from './middleware/error.js';
dotenv.config();
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' })); app.use(express.json());
app.get('/api/health', (req, res) => res.json({ success: true, message: 'NovaCart API is online' }));
app.use('/api/auth', authRoutes); app.use('/api/products', productRoutes); app.use('/api/categories', categoryRoutes); app.use('/api/cart', cartRoutes); app.use('/api/orders', orderRoutes); app.use('/api', reviewRoutes);
app.use('/api/users', userRoutes); app.use('/api/wishlist', wishlistRoutes);
app.use(notFound); app.use(errorHandler);
const port = process.env.PORT || 5000;
if (process.env.NODE_ENV !== 'test') connectDatabase().then(() => app.listen(port, () => console.log(`NovaCart API listening on ${port}`))).catch((error) => console.error('Database connection failed:', error.message));
export default app;
